name: "Slack pr open notification"
author: "erskaggs"
description: "Use github actions to notify slack that a pull request has been opened."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-pull-request"
  color: "green"
